### ISSUE TITLE
SaveAndNew Command

### ISSUE THREAD

**Issue by TarrahArshad** [DevExpress-Examples/mvvmexpenses-sample-application-t254492#2]
how to implement SaveAndNew Command in SingleObjectViewModel.cs ?
and refresh and resset changes ?

**Comment by SvetlanaPN** [comment]
Hi, 

Please [submit a new ticket](https://www.devexpress.com/Support/Center/Question/Create) to our Support Center. Our support engineers will answer you within 24 hours.
