### ISSUE TITLE
Please upgrade to DevExpress WinForm 20.2.x

### ISSUE THREAD

**Issue by donhuvy** [DevExpress-Examples/mvvmexpenses-sample-application-t254492#3]
![image](https://user-images.githubusercontent.com/1328316/97467258-974a5b00-1976-11eb-9699-0084572aeb91.png)

**Comment by NadezhdaBobrovaDX** [comment]
Hello,

To update a project to a required version of our components, I suggest you use our Project Converter. For this, please perform steps from [our article](https://docs.devexpress.com/GeneralInformation/2221/installation/upgrade-notes). If it does not help and errors are shown, please create a ticket in [our Support Center](https://supportcenter.devexpress.com/ticket/create).
